name: flutter_playground
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  go_router: ^14.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  logging: ^1.2.0
  flutter_bloc: ^8.1.5
  flutter_form_builder: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
  output_dir: lib/l10n/generated