name: flutter_playground
description: "My Flutter Playground"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  go_router: ^14.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  logging: ^1.2.0
  flutter_bloc: ^8.1.5
  flutter_form_builder: ^9.2.1
  flutter_native_splash: ^2.4.0
  dio: ^5.7.0
  pocketbase: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.2

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_screen.png

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
  output_dir: lib/l10n/generated