// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyAxSlF4Xnz3LAHm9ykuHRllGbYWLBO0Q',
    appId: '1:380612199205:web:329461ddd9dc02ac9e90cc',
    messagingSenderId: '380612199205',
    projectId: 'flutterplaygroundfb',
    authDomain: 'flutterplaygroundfb.firebaseapp.com',
    storageBucket: 'flutterplaygroundfb.appspot.com',
    measurementId: 'G-YK957G2S1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmTRdhA9O0K4TW_PsRp1snXhYCnHhQuzA',
    appId: '1:380612199205:android:ec1a9e4d482ff0969e90cc',
    messagingSenderId: '380612199205',
    projectId: 'flutterplaygroundfb',
    storageBucket: 'flutterplaygroundfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAI3bXQGO2LW38xYEjcVDrsF_TnV3fQnk',
    appId: '1:380612199205:ios:1b5ec9c2955b24f89e90cc',
    messagingSenderId: '380612199205',
    projectId: 'flutterplaygroundfb',
    storageBucket: 'flutterplaygroundfb.appspot.com',
    iosBundleId: 'com.example.flutterPlayground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAI3bXQGO2LW38xYEjcVDrsF_TnV3fQnk',
    appId: '1:380612199205:ios:1b5ec9c2955b24f89e90cc',
    messagingSenderId: '380612199205',
    projectId: 'flutterplaygroundfb',
    storageBucket: 'flutterplaygroundfb.appspot.com',
    iosBundleId: 'com.example.flutterPlayground',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyAxSlF4Xnz3LAHm9ykuHRllGbYWLBO0Q',
    appId: '1:380612199205:web:ea762e9e7a7b75db9e90cc',
    messagingSenderId: '380612199205',
    projectId: 'flutterplaygroundfb',
    authDomain: 'flutterplaygroundfb.firebaseapp.com',
    storageBucket: 'flutterplaygroundfb.appspot.com',
    measurementId: 'G-G7JZWS64RC',
  );
}
